{{- $ingressConfigurations := list
  (dict "name" "librespeed" "class" "nginx")
  (dict "name" "librespeed-home" "class" "nginx-home")
}}

{{- range $config := $ingressConfigurations }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: {{ index $config "class" }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 256M
  labels:
    app.kubernetes.io/instance: librespeed-home
    app.kubernetes.io/name: librespeed-home
  name: {{ index $config "name" }}
spec:
  rules:
    - host: speed.ivanchenko.io
      http:
        paths:
          - backend:
              service:
                name: librespeed-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - speed.ivanchenko.io
      secretName: librespeed-tls
---
{{- end }}
