iso_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/test/39_Beta/Server/x86_64/iso/Fedora-Server-dvd-x86_64-39_Beta-1.1.iso"
iso_checksum: "sha256:35de29c04ada9379679f2eec9ec7b73ecab5e1070e2e97fc09f4f81ea102d569"
timezone: Etc/UTC
dhcp_proxy: true
dns_server: 1.1.1.1
ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
