grafana-operator:
  crds:
    immutable: false

helpers:
  oidcClients:
    - name: grafana
      spec:
        clientID: "30704bb7-54cd-4f06-86ca-0cd49fcb441d"
        callbackUrls:
          - "https://grafana.ivanchenko.io/login/generic_oauth"
        allowedUserGroups:
          - name: admins
            namespace: pocket-id
        logo:
          autoGenerate: false
        secret:
          name: grafana-oidc
  infisicalSecrets:
    # Infisical path with keys: TELEGRAM_BOTTOKEN, TELEGRAM_CHATID, HEALTHCHECKS_URL.
    - name: grafana-alerting
      infisical:
        path: "/monitoring/grafana-alerting"
      template:
        includeAllSecrets: true
        metadata:
          labels:
            app.kubernetes.io/managed-by: grafana-operator
  backups:
    - pvcName: grafana-pvc
      resticRepoSuffix: grafana
      moverSecurityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
