grafana-operator:
  crds:
    immutable: false

helpers:
  infisicalSecrets:
    - name: grafana-oauth
      infisical:
        path: "/monitoring/grafana"
    # Infisical path with keys: TELEGRAM_BOTTOKEN, TELEGRAM_CHATID, HEALTHCHECKS_URL.
    - name: grafana-alerting
      infisical:
        path: "/monitoring/grafana-alerting"
      template:
        includeAllSecrets: true
        metadata:
          labels:
            app.kubernetes.io/managed-by: grafana-operator
  backups:
    - pvcName: grafana-pvc
      resticRepoSuffix: grafana
      moverSecurityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
