apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vpn-secret
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/media/vpn"
  managedSecretReference:
    secretName: vpn-secret
    secretNamespace: media
