apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        OPENVPN_USER: {{` "{{ .openvpn_user }}" `}}
        OPENVPN_PASSWORD: {{` "{{ .openvpn_password }}" `}}
        SERVER_HOSTNAMES: {{` "{{ .server_hostnames }}" `}}
  data:
    - secretKey: openvpn_user
      remoteRef:
        key: vpn
        property: openvpn_user
    - secretKey: openvpn_password
      remoteRef:
        key: vpn
        property: openvpn_password
    - secretKey: server_hostnames
      remoteRef:
        key: vpn
        property: server_hostnames