kube-prometheus-stack:
  grafana:
    enabled: false
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  prometheus-node-exporter:
    tolerations:
      - operator: "Exists"