core-keeper:
  controllers:
    main:
      replicas: 0
      containers:
        main:
          image:
            repository: escaping/core-keeper-dedicated
            tag: v2.8.1@sha256:87fa7925596264e1460cb6c7c128e9d39ac5445206e04e587993b5d4afa7c90f
          envFrom:
            - secretRef:
                name: core-keeper-secret

  persistence:
    config:
      enabled: true
      suffix: config
      storageClass: longhorn-ssd
      size: 2Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
            - path: /home/steam/core-keeper-data

helpers:
  infisicalSecrets:
    - name: core-keeper-secret
      infisical:
        path: "/core-keeper"
  backups:
    - enabled: false
      pvcName: core-keeper-config
      resticRepoSuffix: core-keeper
