core-keeper:
  controllers:
    main:
      replicas: 0
      containers:
        main:
          image:
            repository: escaping/core-keeper-dedicated
            tag: v2.7.2@sha256:57a339c3d47bdeee1908c80400806783292a9f01a232ca1906eadd8b9f578a30
          envFrom:
            - secretRef:
                name: core-keeper-secret

  persistence:
    config:
      enabled: true
      suffix: config
      storageClass: longhorn-ssd
      size: 2Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
            - path: /home/steam/core-keeper-data

helpers:
  infisicalSecrets:
    - name: core-keeper-secret
      infisical:
        path: "/core-keeper"
  backups:
    - enabled: false
      pvcName: core-keeper-config
      resticRepoSuffix: core-keeper
