apiVersion: v2
name: tailscale
version: 0.0.0
dependencies:
  - name: app-template
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
