app-template:
  serviceAccount:
    tailscale:
      forceRename: tailscale
      staticToken: true
  controllers:
    tailscale:
      serviceAccount:
        name: tailscale
      containers:
        app:
          image:
            repository: ghcr.io/tailscale/tailscale
            tag: v1.102.2@sha256:321ce041508c19079b57a28b6666c8d81ab0b08accc0a2585b3ab663d557ac24
          env:
            TS_HOSTNAME: homelab-router
            TS_USERSPACE: false
            TS_KUBE_SECRET: tailscale-tailscale-sa-token
            TS_ROUTES: 192.168.50.192/26
            TS_AUTHKEY:
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            limits:
              squat.ai/tun: "1"

helpers:
  infisicalSecrets:
    - name: tailscale-auth
      infisical:
        path: "/tailscale"
