app-template:
  serviceAccount:
    tailscale:
      forceRename: tailscale
      staticToken: true
  controllers:
    tailscale:
      serviceAccount:
        name: tailscale
      containers:
        app:
          image:
            repository: ghcr.io/tailscale/tailscale
            tag: v1.102.3@sha256:8c42c4574ab066384fcb72f69e086a2ff1dd3652eb6f56856cee34bcf0d2f680
          env:
            TS_HOSTNAME: homelab-router
            TS_USERSPACE: false
            TS_KUBE_SECRET: tailscale-tailscale-sa-token
            TS_ROUTES: 192.168.50.192/26
            TS_AUTHKEY:
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            limits:
              squat.ai/tun: "1"

helpers:
  infisicalSecrets:
    - name: tailscale-auth
      infisical:
        path: "/tailscale"
