apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        OAUTH_CLIENT_ID: {{` "{{ .oauth_client_id }}" `}}
        OAUTH_CLIENT_SECRET: {{` "{{ .oauth_client_secret }}" `}}
  data:
    - secretKey: oauth_client_id
      remoteRef:
        key: grafana-secret
        property: oauth_client_id
    - secretKey: oauth_client_secret
      remoteRef:
        key: grafana-secret
        property: oauth_client_secret