palworld:
  controllers:
    main:
      replicas: null
      containers:
        main:
          image:
            repository: thijsvanloef/palworld-server-docker
            tag: latest@sha256:85ae20d8756dd398ec24f4253a59b80907e5ffe411148a67b2c80c4527a8855e
          env:
            PUID: 1000
            PGID: 1000
            PORT: 8211
            QUERY_PORT: 27016
            PLAYERS: 16
            MULTITHREADING: "true"
            COMMUNITY: "false"
            UPDATE_ON_BOOT: "true"
            RCON_ENABLED: "true"
            RCON_PORT: 25575
            SERVER_NAME: Palworld Server
            TZ: Europe/Kyiv
          envFrom:
            - secretRef:
                name: palworld-secret

  service:
    main:
      controller: main
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "palworld.ivanchenko.io"
        lbipam.cilium.io/lb-ipam-ips: 46.38.230.69
        lbipam.cilium.io/sharing-key: vps-tunnel
        lbipam.cilium.io/sharing-cross-namespace: "*"
      labels:
        expose-public: "true"
      ports:
        game:
          port: 8211
          protocol: UDP
        query:
          port: 27016
          protocol: UDP
    internal:
      controller: main
      type: LoadBalancer
      annotations:
        internal.ivanchenko.io/hostname: "palworld.ivanchenko.io"
      loadBalancerIP: 192.168.50.241
      ports:
        game:
          port: 8211
          protocol: UDP
        query:
          port: 27016
          protocol: UDP

  persistence:
    config:
      enabled: true
      suffix: config
      storageClass: longhorn-ssd
      size: 20Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
            - path: /palworld

helpers:
  infisicalSecrets:
    - name: palworld-secret
      infisical:
        path: "/palworld"
  backups:
    - pvcName: palworld-config
      resticRepoSuffix: palworld
