librespeed:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/librespeed/speedtest
            tag: 6.1.0@sha256:b6b0890047e833158370d59ed5ef289b3e67a58f4a363cd37ef5c09d170d8543
          env:
            MODE: standalone

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8080
    ext-lb:
      controller: main
      annotations:
        lbipam.cilium.io/lb-ipam-ips: 46.38.230.69
        lbipam.cilium.io/sharing-key: vps-tunnel
        lbipam.cilium.io/sharing-cross-namespace: "*"
      labels:
        expose-public: "true"
      type: LoadBalancer
      ports:
        http:
          port: 8080

  route:
    main:
      hostnames:
        - speed.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
        - name: public-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: main
