librespeed:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/librespeed/speedtest
            tag: 6.0.2@sha256:871ec7a1c908e7c9288e51e074b321088a297c37fc672a4c882b0309f61ddef7
          env:
            MODE: standalone

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8080
    ext-lb:
      controller: main
      annotations:
        lbipam.cilium.io/lb-ipam-ips: 46.38.230.69
        lbipam.cilium.io/sharing-key: vps-tunnel
        lbipam.cilium.io/sharing-cross-namespace: "*"
      labels:
        expose-public: "true"
      type: LoadBalancer
      ports:
        http:
          port: 8080

  route:
    main:
      hostnames:
        - speed.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
        - name: public-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: main
