librespeed:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/librespeed/speedtest
            tag: 5.5.1@sha256:1c8ca636a9b68d023c819c5ce6e7fab3f5214b963138eb9ef6aaddf9ae111c77
          env:
            MODE: standalone

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8080
    ext-lb:
      controller: main
      annotations:
        lbipam.cilium.io/lb-ipam-ips: 46.38.230.69
        lbipam.cilium.io/sharing-key: vps-tunnel
        lbipam.cilium.io/sharing-cross-namespace: "*"
      labels:
        expose-public: "true"
      type: LoadBalancer
      ports:
        http:
          port: 8080

  route:
    main:
      hostnames:
        - speed.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: main
    main-public:
      hostnames:
        - speed-public.ivanchenko.io
      parentRefs:
        - name: public-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: main
