apiVersion: v2
name: volsync
version: 0.0.0
dependencies:
  - name: volsync
    version: 0.12.1
    repository: https://backube.github.io/helm-charts
  - name: snapshot-controller
    version: 4.0.2
    repository: https://piraeus.io/helm-charts
  - name: app-template
    version: 4.0.1
    repository: https://bjw-s-labs.github.io/helm-charts
