qbittorrent:
  global:
    nameOverride: qbittorrent

  defaultPodOptions:
    automountServiceAccountToken: false

  controllers:
    main:
      pod:
        nodeSelector:
          topology.kubernetes.io/region: cloud
        securityContext:
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        main:
          image:
            repository: linuxserver/qbittorrent
            tag: 4.6.0
          env:
            PUID: 568
            PGID: 568
            TZ: Etc/UTC
            WEBUI_PORT: 8080
          securityContext:
            runAsUser: 0
            runAsGroup: 0

        gluetun:
          dependsOn: main
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.36.0
          env:
            VPN_SERVICE_PROVIDER: protonvpn
            VPN_PORT_FORWARDING: on
          envFrom:
            - secretRef:
                name: vpn-secret
          securityContext:
            capabilities:
              add:
                - NET_ADMIN

        port-forward:
          dependsOn: gluetun
          image:
            repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
            tag: "1.0"
          env:
            - name: QBITTORRENT_SERVER
              value: localhost
            - name: QBITTORRENT_PORT
              value: "8080"
            - name: PORT_FORWARDED
              value: "/tmp/gluetun/forwarded_port"

  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "qBittorrent"
        gethomepage.dev/description: "Free and reliable P2P Bittorrent client"
        gethomepage.dev/group: "Dynamic"
        gethomepage.dev/icon: "qbittorrent.png"
        gethomepage.dev/widget.type: "qbittorrent"
        gethomepage.dev/widget.url: "http://media-qbittorrent.media.svc.cluster.local:8080"
        gethomepage.dev/widget.username: "username"
        gethomepage.dev/widget.password: "password"
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=qbittorrent"
        nginx.ingress.kubernetes.io/auth-url: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/start
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
      ingressClassName: "nginx"
      hosts:
        - host: &host "qbittorrent.ivanchenko.io"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: qbittorrent-tls
          hosts:
            - *host

  persistence:
    config:
      enabled: true
      size: 200Mi
      advancedMounts:
        main:
          main:
            - path: /config

    downloads:
      type: persistentVolumeClaim
      existingClaim: media-pvc
      advancedMounts:
        main:
          main:
            - path: /downloads
              subPath: /downloads

    gluetun-data:
      type: emptyDir
      advancedMounts:
        main:
          gluetun:
            - path: /tmp/gluetun
          port-forward:
            - path: /tmp/gluetun
              readOnly: true

rdtclient:
  global:
    nameOverride: rdtclient

  defaultPodOptions:
    automountServiceAccountToken: false

  controllers:
    main:
      pod:
        securityContext:
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        main:
          image:
            repository: rogerfar/rdtclient
            tag: 2.0.49
          env:
            PUID: 568
            PGID: 568
            TZ: Etc/UTC
          securityContext:
            runAsUser: 0
            runAsGroup: 0

  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 6500

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "rdt-client"
        gethomepage.dev/description: "Real-Debrid Client Proxy"
        gethomepage.dev/group: "Dynamic"
        gethomepage.dev/icon: "real-debrid.svg"
        gethomepage.dev/widget.type: "qbittorrent"
        gethomepage.dev/widget.url: "http://media-rdtclient.media.svc.cluster.local:6500"
        gethomepage.dev/widget.username: "username"
        gethomepage.dev/widget.password: "password"
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=rdtclient"
        nginx.ingress.kubernetes.io/auth-url: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/start
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
      ingressClassName: "nginx"
      hosts:
        - host: &host "rdtclient.ivanchenko.io"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: rdtclient-tls
          hosts:
            - *host

  persistence:
    config:
      enabled: true
      size: 200Mi
      advancedMounts:
        main:
          main:
            - path: /data/db

    downloads:
      type: persistentVolumeClaim
      existingClaim: media-pvc
      advancedMounts:
        main:
          main:
            - path: /data/downloads
              subPath: /downloads

prowlarr:
  global:
    nameOverride: prowlarr

  defaultPodOptions:
    automountServiceAccountToken: false

  controllers:
    main:
      pod:
        securityContext:
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        main:
          image:
            repository: linuxserver/prowlarr
            tag: 1.9.4
          env:
            PUID: 568
            PGID: 568
            TZ: Etc/UTC
          securityContext:
            runAsUser: 0
            runAsGroup: 0

  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 9696

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "prowlarr"
        gethomepage.dev/description: "The Ultimate Indexer Manager"
        gethomepage.dev/group: "Dynamic"
        gethomepage.dev/icon: "prowlarr.png"
        gethomepage.dev/widget.type: "prowlarr"
        gethomepage.dev/widget.url: "http://media-prowlarr.media.svc.cluster.local:9696"
        gethomepage.dev/widget.key: "0b7b43d4e25a46428ce144f6c22ef2f4"
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=prowlarr"
        nginx.ingress.kubernetes.io/auth-url: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/start
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
      ingressClassName: "nginx"
      hosts:
        - host: &host "prowlarr.ivanchenko.io"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: prowlarr-tls
          hosts:
            - *host

  persistence:
    config:
      enabled: true
      size: 200Mi
      advancedMounts:
        main:
          main:
            - path: /config

radarr:
  global:
    nameOverride: radarr

  defaultPodOptions:
    automountServiceAccountToken: false

  controllers:
    main:
      pod:
        securityContext:
          fsGroup: 568
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        main:
          image:
            repository: linuxserver/radarr
            tag: 5.1.3
          env:
            PUID: 568
            PGID: 568
            TZ: Etc/UTC
          securityContext:
            runAsUser: 0
            runAsGroup: 0

  service:
    main:
      type: ClusterIP
      ports:
        http:
          port: 7878

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "radarr"
        gethomepage.dev/description: "Smart PVR for movies"
        gethomepage.dev/group: "Dynamic"
        gethomepage.dev/icon: "radarr.png"
        gethomepage.dev/widget.type: "radarr"
        gethomepage.dev/widget.url: "http://media-radarr.media.svc.cluster.local:7878"
        gethomepage.dev/widget.key: "0b7b43d4e25a46428ce144f6c22ef2f4"
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=radarr"
        nginx.ingress.kubernetes.io/auth-url: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://auth.ivanchenko.io/outpost.goauthentik.io/start
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
      ingressClassName: "nginx"
      hosts:
        - host: &host "radarr.ivanchenko.io"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: radarr-tls
          hosts:
            - *host

  persistence:
    config:
      enabled: true
      size: 200Mi
      advancedMounts:
        main:
          main:
            - path: /config
    downloads:
      type: persistentVolumeClaim
      existingClaim: media-pvc
      advancedMounts:
        main:
          main:
            - path: /downloads
              subPath: /downloads
            - path: /movies
              subPath: /movies