kaneo:
  controllers:
    api:
      containers:
        main:
          image:
            repository: ghcr.io/usekaneo/api
            tag: 2.34.0@sha256:e06753effedfc9871b1a4825f71ffb0efe57cdc50e28a10de8f29df81161f67f
          envFrom:
            - secretRef:
                name: kaneo-s3
          env:
            KANEO_CLIENT_URL: "https://kaneo.ivanchenko.io"
            KANEO_API_URL: "https://kaneo.ivanchenko.io"
            DISABLE_GUEST_ACCESS: 'true'
            DISABLE_REGISTRATION: 'true'
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: kaneo-secret
                  key: dburi
            AUTH_SECRET:
              valueFrom:
                secretKeyRef:
                  name: kaneo-secret
                  key: AUTH_SECRET
            CUSTOM_OAUTH_CLIENT_ID: kaneo
            CUSTOM_OAUTH_CLIENT_SECRET:
              valueFrom:
                secretKeyRef:
                  name: kaneo-secret
                  key: CUSTOM_OAUTH_CLIENT_SECRET
            CUSTOM_OAUTH_DISCOVERY_URL: https://id.ivanchenko.io/.well-known/openid-configuration
            CUSTOM_OAUTH_SCOPES: "openid,profile,email"
            S3_ENDPOINT: https://s3.ivanchenko.io
            S3_BUCKET: kaneo
            

    web:
      containers:
        main:
          image:
            repository: ghcr.io/usekaneo/web
            tag: 2.34.0@sha256:30722f9ac9f0627ea06f127c1dd936427561266f47bd19056c8e7232ec67f451
          env:
            KANEO_API_URL: "https://kaneo.ivanchenko.io"
            KANEO_CLIENT_URL: "https://kaneo.ivanchenko.io"

  service:
    api:
      controller: api
      ports:
        http:
          port: 1337

    web:
      controller: web
      ports:
        http:
          port: 5173

  route:
    main:
      hostnames:
        - kaneo.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: kaneo-web
              port: 5173
        - matches:
            - path:
                type: PathPrefix
                value: /api/
          backendRefs:
            - name: kaneo-api
              port: 1337

helpers:
  infisicalSecrets:
    - name: kaneo-secret
      type: kubernetes.io/basic-auth
      infisical:
        path: "/kaneo"
    - name: kaneo-s3
      namespace: kaneo
      infisical:
        path: "/versitygw"
      template:
        data:
          S3_ACCESS_KEY_ID: "{{ .rootAccessKeyId.Value }}"
          S3_SECRET_ACCESS_KEY: "{{ .rootSecretAccessKey.Value }}"
  backups:
    - pvcName: kaneo-postgres-1
      resticRepoSuffix: kaneo/postgres
      unlock: "2026-09-11"
      moverSecurityContext:
        fsGroup: 26
        runAsGroup: 26
        runAsNonRoot: true
        runAsUser: 26
