kaneo:
  controllers:
    api:
      containers:
        main:
          image:
            repository: ghcr.io/usekaneo/api
            tag: 2.6.8@sha256:3bff1d8b5c7a434c020658c4606e67d11b3eeed2ab7e11107a533c05c38cbcbe
          envFrom:
            - secretRef:
                name: kaneo-s3
          env:
            KANEO_CLIENT_URL: "https://kaneo.ivanchenko.io"
            KANEO_API_URL: "https://kaneo.ivanchenko.io"
            DISABLE_GUEST_ACCESS: 'true'
            DISABLE_REGISTRATION: 'true'
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: kaneo-secret
                  key: dburi
            AUTH_SECRET:
              valueFrom:
                secretKeyRef:
                  name: kaneo-secret
                  key: AUTH_SECRET
            CUSTOM_OAUTH_CLIENT_ID: kaneo
            CUSTOM_OAUTH_CLIENT_SECRET:
              valueFrom:
                secretKeyRef:
                  name: kaneo-secret
                  key: CUSTOM_OAUTH_CLIENT_SECRET
            CUSTOM_OAUTH_DISCOVERY_URL: https://id.ivanchenko.io/.well-known/openid-configuration
            S3_ENDPOINT: https://s3.ivanchenko.io
            S3_BUCKET: kaneo
            

    web:
      containers:
        main:
          image:
            repository: ghcr.io/usekaneo/web
            tag: 2.6.0@sha256:e15e058c2884e136e9048977758dff54c313e349752fd47e5db9f78bac7ebcf9
          env:
            KANEO_API_URL: "https://kaneo.ivanchenko.io"
            KANEO_CLIENT_URL: "https://kaneo.ivanchenko.io"

  service:
    api:
      controller: api
      ports:
        http:
          port: 1337

    web:
      controller: web
      ports:
        http:
          port: 5173

  route:
    main:
      hostnames:
        - kaneo.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: kaneo-web
              port: 5173
        - matches:
            - path:
                type: PathPrefix
                value: /api/
          backendRefs:
            - name: kaneo-api
              port: 1337

helpers:
  infisicalSecrets:
    - name: kaneo-secret
      type: kubernetes.io/basic-auth
      infisical:
        path: "/kaneo"
    - name: kaneo-s3
      namespace: kaneo
      infisical:
        path: "/versitygw"
      template:
        data:
          S3_ACCESS_KEY_ID: "{{ .rootAccessKeyId.Value }}"
          S3_SECRET_ACCESS_KEY: "{{ .rootSecretAccessKey.Value }}"
