authentik:
  global:
    envFrom:
      - secretRef:
          name: authentik-secret

  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - &host auth.ivanchenko.io
      tls:
        - secretName: authentik-tls
          hosts:
            - *host

  postgresql:
    enabled: true
    auth:
      existingSecret: "authentik-postgresql"

  redis:
    enabled: true
