apiVersion: v2
name: loki
version: 0.0.0
dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 5.41.1
  - name: fluent-bit
    repository: https://grafana.github.io/helm-charts
    version: 2.6.0