apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: idrivee2-secret
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/longhorn/idrivee2"
  managedSecretReference:
    secretName: idrivee2-secret
    secretNamespace: longhorn-system