apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idrivee2-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: {{` "{{ .access_key_id }}" `}}
        AWS_ENDPOINTS: {{` "{{ .endpoints }}" `}}
        AWS_SECRET_ACCESS_KEY: {{` "{{ .secret_access_key }}" `}}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: idrivee2
        property: access_key_id
    - secretKey: endpoints
      remoteRef:
        key: idrivee2
        property: endpoints
    - secretKey: secret_access_key
      remoteRef:
        key: idrivee2
        property: secret_access_key