plexio:
  image:
    repository: registry.ivanchenko.io/plexio
    tag: "main-954807be"
  frontapp:
    image:
      repository: registry.ivanchenko.io/plexio-frontapp
      tag: "main-0de3ae87"
  env:
    - name: REDIS_HOST
      value: 'plexio-redis-master.plexio'
    - name: SENTRY_DSN
      valueFrom:
        secretKeyRef:
          name: sentry-secret
          key: SENTRY_DSN
    - name: SENTRY_ENVIRONMENT
      value: 'beta'
    - name: CORS_ORIGIN_REGEX
      value: '.*plexio.stream|.*strem.io|.*stremio.com'
    - name: MATCHING_PLEX_ADDRESS
      value: http://localhost:32400
