apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflared-credentials
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/cloudflare"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: cloudflared-credentials
    secretNamespace: cloudflared
    template:
      data:
        credentials.json: '{{ `{{ .cloudflared-credentials.Value }}` }}'
