apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drone-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        DRONE_GITHUB_CLIENT_ID: {{` "{{ .drone_github_client_id }}" `}}
        DRONE_GITHUB_CLIENT_SECRET: {{` "{{ .drone_github_client_secret }}" `}}
        DRONE_RPC_SECRET: {{` "{{ .drone_rpc_secret }}" `}}
  data:
    - secretKey: drone_github_client_id
      remoteRef:
        key: drone
        property: drone_github_client_id
    - secretKey: drone_github_client_secret
      remoteRef:
        key: drone
        property: drone_github_client_secret
    - secretKey: drone_rpc_secret
      remoteRef:
        key: drone
        property: drone_rpc_secret