apiVersion: v2
name: telemetry
version: 0.0.0
dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.95.0
    repository: https://victoriametrics.github.io/helm-charts/
  - name: prometheus-operator-crds
    version: 32.0.1
    repository: https://prometheus-community.github.io/helm-charts/
  - name: vector
    version: 0.59.0
    repository: https://helm.vector.dev
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
