factorio:
  controllers:
    main:
      containers:
        main:
          image:
            repository: factoriotools/factorio
            tag: 2.1.20@sha256:e91a03290ef860ee8ec1a15bd6bb63732c1c89c4cb7d80cff8d49bc642e01913

  service:
    main:
      controller: main
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "factorio.ivanchenko.io"
        lbipam.cilium.io/lb-ipam-ips: 46.38.230.69
        lbipam.cilium.io/sharing-key: vps-tunnel
        lbipam.cilium.io/sharing-cross-namespace: "*"
      labels:
        expose-public: "true"
      ports:
        game:
          port: 34197
          protocol: UDP
        query:
          port: 27015
          protocol: TCP
    internal:
      controller: main
      type: LoadBalancer
      annotations:
        internal.ivanchenko.io/hostname: "factorio.ivanchenko.io"
      loadBalancerIP: 10.10.61.230
      ports:
        game:
          port: 34197
          protocol: UDP
        query:
          port: 27015
          protocol: TCP

  persistence:
    server:
      enabled: true
      storageClass: longhorn-ssd
      size: 1Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
            - path: /factorio

helpers:
  backups:
    - pvcName: factorio
      resticRepoSuffix: factorio
      moverSecurityContext:
        fsGroup: 845
        runAsGroup: 845
        runAsUser: 845
