apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-router
spec:
  bgpInstances:
    - name: "instance-router"
      localASN: 64512
      peers:
        - name: "router"
          peerASN: 64512
          peerAddress: {{ .Values.ciliumBGP.routerAddress | quote }}
          peerConfigRef:
            name: router-peer-config
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: router-peer-config
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "router"
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: advertise-router
  labels:
    advertise: "router"
spec:
  advertisements:
    - advertisementType: PodCIDR
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - key: somekey
            operator: NotIn
            values:
              - never-used-value
