apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: services-pool
spec:
  blocks:
    - cidr: "10.10.61.0/24"
  serviceSelector:
    matchExpressions:
      - key: expose-public
        operator: DoesNotExist
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-pool
spec:
  serviceSelector:
    matchLabels:
      expose-public: "true"
  blocks:
    - cidr: "46.38.230.69/32"
