---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_POSTGRESQL__PASSWORD: '5fnApcMMwPXxrHK8/BKga7NkiwfvYLhOdjXJaN/WaYPfd2yH'
  AUTHENTIK_SECRET_KEY: 'NHJfAIFPXQe84bd7pzFN1kJfbRTsfiWmNX5xjjQWvURlhL/b'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
stringData:
  postgresql-password: '5fnApcMMwPXxrHK8/BKga7NkiwfvYLhOdjXJaN/WaYPfd2yH'
  postgresql-postgres-password: '5fnApcMMwPXxrHK8/BKga7NkiwfvYLhOdjXJaN/WaYPfd2yH'
