---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        AUTHENTIK_POSTGRESQL__PASSWORD: {{` "{{ .authentik_postgresql__password }}" `}}
        AUTHENTIK_SECRET_KEY: {{` "{{ .authentik_secret_key }}" `}}
  data:
    - secretKey: authentik_postgresql__password
      remoteRef:
        key: authentik
        property: authentik_postgresql__password
    - secretKey: authentik_secret_key
      remoteRef:
        key: authentik
        property: authentik_secret_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        postgresql-password: {{` "{{ .authentik_postgresql__password }}" `}}
        postgresql-postgres-password: {{` "{{ .postgresql_postgres_password }}" `}}
  data:
    - secretKey: authentik_postgresql__password
      remoteRef:
        key: authentik
        property: authentik_postgresql__password
    - secretKey: postgresql_postgres_password
      remoteRef:
        key: authentik
        property: postgresql_postgres_password
