metal:
  children:
    metal:
      hosts:
        metal0:
          ansible_host: 192.168.1.222
          mac: '6C:4B:90:A2:75:D7'
          disk: sda
          network_interface: eno1
          master: true
