apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: paperless-secret
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/paperless"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: paperless-secret
    secretNamespace: paperless-ngx
