apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: b2-secret
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/longhorn/b2"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: b2-secret
    secretNamespace: longhorn-system
