apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        IMMICH_API_KEY: {{` "{{ .immich_api_key }}" `}}
  data:
    - secretKey: immich_api_key
      remoteRef:
        key: homepage
        property: immich_api_key
