apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: core-keeper-secret
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/core-keeper"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: cloudflared-credentials
    secretNamespace: cloudflared
