apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: core-keeper-restic-config
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/common/restic"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: core-keeper-restic-config
    secretNamespace: core-keeper
    template:
      includeAllSecrets: true
      data:
        RESTIC_REPOSITORY: '{{ `{{ .RESTIC_BUCKET.Value }}/core-keeper` }}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: core-keeper-backup
spec:
  sourcePVC: core-keeper-config
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 14
    repository: core-keeper-restic-config
    retain:
      hourly: 12
      daily: 7
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone
    storageClassName: longhorn-ssd-backup
    volumeSnapshotClassName: longhorn-snapshot-vsc
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: datavol-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: core-keeper-restic-config
    # Use an existing PVC, don't provision a new one
    destinationPVC: core-keeper-config
    copyMethod: Direct
  moverSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
    runAsUser: 1000
    runAsGroup: 1000
