immich:
  controllers:
    main:
      containers:
        main:
          env:
            DB_HOSTNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-app
                  key: host
            DB_USERNAME:
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-user
                  key: username
            DB_DATABASE_NAME:
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-app
                  key: dbname
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-user
                  key: password

  immich:
    persistence:
      library:
        existingClaim: photo-library

  valkey:
    enabled: true
    persistence:
      data:
        enabled: true
        size: 1Gi
        storageClass: longhorn-ssd
        accessMode: ReadWriteOnce

  server:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.7.3@sha256:00cd2d57e4d9310a4aeac3c23f249af1eadbc1802746e1178589ef0a49374cef
    route:
      main:
        hostnames:
          - immich.ivanchenko.io
        parentRefs:
          - name: internal-gw
            namespace: envoy-gateway
            sectionName: https

  machine-learning:
    enabled: true
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.7.3@sha256:ccea091ea02086bb9a4712497a6db945a10548f7817101fa18e9b20fdb4f746f

helpers:
  infisicalSecrets:
    - name: immich-postgres-user
      infisical:
        path: "/immich/postgres-user"
  backups:
    - pvcName: photo-library
      resticRepoSuffix: photo-library
      schedule: "0 0 * * *"
    - pvcName: immich-postgres-1
      resticRepoSuffix: immich/postgres
      schedule: "0 0 * * *"
      moverSecurityContext:
        fsGroup: 26
        runAsGroup: 26
        runAsNonRoot: true
        runAsUser: 26
