actualbudget:
  defaultPodOptions:
    automountServiceAccountToken: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - jupiter

  controllers:
    actualbudget:
      containers:
        main:
          image:
            repository: actualbudget/actual-server
            tag: 26.3.0@sha256:eb8bc26f53025e07e464594c12d77c52c4b95840c8dadd9b95c4f0c4660f8ad2
          env:
            ACTUAL_OPENID_SERVER_HOSTNAME: https://budget.ivanchenko.io
            ACTUAL_OPENID_ENFORCE: true
            ACTUAL_OPENID_AUTH_METHOD: openid
          envFrom:
            - secretRef:
                name: actualbudget-secret

    bank-sync-web:
      pod:
        imagePullSecrets:
          - name: ghcr-login-secret
      containers:
        main:
          image:
            repository: ghcr.io/vanchaxy/bank-sync
            tag: sha-9213397

  service:
    actualbudget:
      controller: actualbudget
      type: ClusterIP
      ports:
        http:
          port: 5006
    bank-sync-web:
      controller: bank-sync-web
      type: ClusterIP
      ports:
        http:
          port: 8000

  route:
    actualbudget:
      hostnames:
        - budget.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: actualbudget
    bank-sync-web:
      hostnames:
        - bank-sync.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: bank-sync-web

  persistence:
    data:
      enabled: true
      storageClass: longhorn-ssd
      size: 1Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        actualbudget:
          main:
            - path: /data
    bank-sync:
      enabled: true
      storageClass: longhorn-ssd
      size: 1Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        bank-sync-web:
          main:
            - path: /data

helpers:
  ghcrSecret:
    enabled: true
  infisicalSecrets:
    - name: actualbudget-secret
      infisical:
        path: "/actualbudget"
  backups:
    - pvcName: actualbudget-data
      resticRepoSuffix: actualbudget/data
    - pvcName: actualbudget-bank-sync
      resticRepoSuffix: actualbudget/bank-sync
