actualbudget:
  defaultPodOptions:
    automountServiceAccountToken: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - jupiter

  controllers:
    actualbudget:
      containers:
        main:
          image:
            repository: actualbudget/actual-server
            tag: 26.2.0@sha256:c34346f87725b9cce5dca5af1a2a9b989127d592cc4c6af5cf4652d4a86def90
          env:
            ACTUAL_OPENID_SERVER_HOSTNAME: https://budget.ivanchenko.io
            ACTUAL_OPENID_ENFORCE: true
            ACTUAL_OPENID_AUTH_METHOD: openid
          envFrom:
            - secretRef:
                name: actualbudget-secret

    bank-sync-web:
      containers:
        main:
          image:
            repository: ghcr.io/coleifer/sqlite-web
            tag: 0.7.0
          args:
            - -H
            - 0.0.0.0
            - /data/sqlite.db

    bank-sync:
      type: cronjob
      cronjob:
        schedule: "0 11,15,20 * * *"
        concurrencyPolicy: Forbid
        startingDeadlineSeconds: 120
        backoffLimit: 0
        successfulJobsHistory: 3
        failedJobsHistory: 3
      pod:
        imagePullSecrets:
          - name: ghcr-login-secret
      containers:
        main:
          image:
            repository: ghcr.io/vanchaxy/bank-sync
            tag: sha-59b2244
          envFrom:
            - secretRef:
                name: actualbudget-secret

    bank-sync-skip-download:
      type: cronjob
      cronjob:
        schedule: "0 0-10,12-14,16-19,21-23 * * *"
        concurrencyPolicy: Forbid
        startingDeadlineSeconds: 120
        backoffLimit: 0
        successfulJobsHistory: 3
        failedJobsHistory: 3
      pod:
        imagePullSecrets:
          - name: ghcr-login-secret
      containers:
        main:
          image:
            repository: ghcr.io/vanchaxy/bank-sync
            tag: sha-59b2244
          args: ['--skip-download']
          envFrom:
            - secretRef:
                name: actualbudget-secret

  service:
    actualbudget:
      controller: actualbudget
      type: ClusterIP
      ports:
        http:
          port: 5006
    bank-sync-web:
      controller: bank-sync-web
      type: ClusterIP
      ports:
        http:
          port: 8080

  route:
    actualbudget:
      hostnames:
        - budget.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: actualbudget
    bank-sync-web:
      hostnames:
        - bank-sync.ivanchenko.io
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      rules:
        - backendRefs:
            - identifier: bank-sync-web

  persistence:
    data:
      enabled: true
      storageClass: longhorn-ssd
      size: 1Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        actualbudget:
          main:
            - path: /data
    bank-sync:
      enabled: true
      storageClass: longhorn-ssd
      size: 1Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        bank-sync:
          main:
            - path: /data
        bank-sync-skip-download:
          main:
            - path: /data
        bank-sync-web:
          main:
            - path: /data

helpers:
  ghcrSecret:
    enabled: true
  infisicalSecrets:
    - name: actualbudget-secret
      infisical:
        path: "/actualbudget"
  backups:
    - pvcName: actualbudget-data
      resticRepoSuffix: actualbudget/data
    - pvcName: actualbudget-bank-sync
      resticRepoSuffix: actualbudget/bank-sync
