gateway-helm:
  config:
    envoyGateway:
      extensionApis:
        enableBackend: true
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
