apiVersion: v2
name: crowdsec
version: 0.0.0
dependencies:
  - name: crowdsec
    version: 0.24.2
    repository: https://crowdsecurity.github.io/helm-charts
  - name: app-template
    version: 5.2.1
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: blocklist-mirror
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
