apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/authentik"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: authentik-secret
    secretNamespace: authentik
    template:
      data:
        AUTHENTIK_SECRET_KEY: '{{ `{{ .secret_key.Value }}` }}'
        AUTHENTIK_BOOTSTRAP_EMAIL: '{{ `{{ .bootstrap_email.Value }}` }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ `{{ .bootstrap_password.Value }}` }}'
        AUTHENTIK_BOOTSTRAP_TOKEN: '{{ `{{ .bootstrap_token.Value }}` }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: '{{ `{{ .postgres_user_password.Value }}` }}'
