apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik-postgresql
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/authentik"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: authentik-postgresql
    secretNamespace: authentik
    template:
      data:
        postgres-password: '{{ `{{ .postgres_admin_password.Value }}` }}'
        password: '{{ `{{ .postgres_user_password.Value }}` }}'
