app = 'chisel'
primary_region = 'fra'

[build]
  image = 'jpillora/chisel:1.11.3'

[experimental]
cmd = ["server", "--reverse"]

[[vm]]
  size = 'shared-cpu-1x'

# chisel
[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 8080

# abiotic
[[services]]
  protocol = 'udp'
  internal_port = 7777

  [[services.ports]]
    port = 7777
