apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-library
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/immich: enabled
spec:
  storageClassName: longhorn-photo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi