apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-immich-redis-master-0
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/immich: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-ssd
