apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-immich-redis-master-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath-ssd-home
