apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-tools
  labels:
    app.kubernetes.io/instance: img-tools
    app.kubernetes.io/name: img-tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: img-tools
      app.kubernetes.io/name: img-tools
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: img-tools
        app.kubernetes.io/name: img-tools
    spec:
      containers:
        - image: tigerj/exiftool
          imagePullPolicy: IfNotPresent
          name: img-tools
          command:
            - sleep
            - "infinity"
          volumeMounts:
            - name: library
              mountPath: /library
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: photo-library
