apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: deny-api-key
spec:
  directResponse:
    statusCode: 403
    contentType: text/plain
    body:
      type: Inline
      inline: "Forbidden"
