necesse:
  controllers:
    main:
      containers:
        main:
          image:
            repository: brammys/necesse-server
            tag: latest@sha256:11ed3707dd05234a24f57c5ecb2e033c9f7992844c44e557da0652b0eacedb4d
          env:
            OWNER: vanchaxy
            GIVE_CLIENTS_POWER: 1
            PAUSE: 1

  service:
    main:
      controller: main
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "necesse.ivanchenko.io"
      ports:
        game:
          port: 14159
          protocol: UDP

  persistence:
    config:
      enabled: true
      suffix: config
      storageClass: longhorn-ssd
      size: 5Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
            - path: /necesse/saves
helpers:
  backups:
    - enabled: false
      pvcName: necesse-config
      resticRepoSuffix: necesse
