necesse:
  controllers:
    main:
      replicas: null
      containers:
        main:
          image:
            repository: brammys/necesse-server
            tag: latest@sha256:9fb2eb0bab9208c2dc4fcba15c54c2abbdd82eab35bfce8e36cb42fe3e40b5ce
          env:
            OWNER: vanchaxy
            GIVE_CLIENTS_POWER: 1
            PAUSE: 1

  service:
    main:
      controller: main
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "necesse.ivanchenko.io"
      ports:
        game:
          port: 14159
          protocol: UDP

  persistence:
    config:
      enabled: true
      suffix: config
      storageClass: longhorn-ssd
      size: 5Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
            - path: /necesse/saves
helpers:
  backups:
    - enabled: false
      pvcName: necesse-config
      resticRepoSuffix: necesse
