pihole:
  dnsmasq:
    customDnsEntries:
      - address=/nas/192.168.178.10

  persistentVolumeClaim:
    enabled: true

  serviceDns:
    annotations:
      metallb.universe.tf/address-pool: home
      metallb.universe.tf/allow-shared-ip: home
    type: LoadBalancer
    externalTrafficPolicy: Cluster

  serviceDhcp:
    annotations:
      metallb.universe.tf/address-pool: home
      metallb.universe.tf/allow-shared-ip: home
    type: LoadBalancer
    externalTrafficPolicy: Cluster

  ingress:
    enabled: true

#    ingressClassName: nginx-home

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx-home
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-passthrough: 'true'

    path: /
    hosts:
      - pihole.ivanchenko.io
    tls:
      - secretName: pihole-tls
        hosts:
          - pihole.ivanchenko.io