pihole:
  dnsmasq:
    customDnsEntries:
      - address=/nas/192.168.178.10

  persistentVolumeClaim:
    enabled: true

  serviceDns:
    annotations:
      metallb.universe.tf/address-pool: home
      metallb.universe.tf/allow-shared-ip: home
    type: LoadBalancer
    externalTrafficPolicy: Cluster

  serviceDhcp:
    annotations:
      metallb.universe.tf/address-pool: home
      metallb.universe.tf/allow-shared-ip: home
    type: LoadBalancer
    externalTrafficPolicy: Cluster
