pihole:
  dnsmasq:
    customDnsEntries:
      - address=/nas/192.168.178.10

  persistentVolumeClaim:
    enabled: true

  serviceWeb:
    loadBalancerIP: 192.168.1.231
    annotations:
      metallb.universe.tf/allow-shared-ip: home
    type: LoadBalancer

  serviceDns:
    loadBalancerIP: 192.168.1.231
    annotations:
      metallb.universe.tf/allow-shared-ip: home
    type: LoadBalancer

  serviceDhcp:
    loadBalancerIP: 192.168.1.231
    annotations:
      metallb.universe.tf/allow-shared-ip: home
    type: LoadBalancer