apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: adguard
spec:
  endpoints:
    - ip:
        address: {{ .Values.adguard.address | quote }}
        port: {{ .Values.adguard.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard
spec:
  hostnames:
    - {{ printf "adguard.%s" .Values.domain }}
  parentRefs:
    - name: internal-gw
      namespace: envoy-gateway
      sectionName: https
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: adguard
