iperf3:
  controllers:
    main:
      containers:
        main:
          image:
            repository: networkstatic/iperf3
            tag: latest@sha256:5b99d62400dc1ffd8ac212dba1c576f27ce4df01d6cd3cba0fbdca6850ca1e90
          args: ["-s"]

  service:
    main:
      controller: main
      type: LoadBalancer
      ports:
        http:
          port: 5201
    public:
      controller: main
      annotations:
        lbipam.cilium.io/lb-ipam-ips: 46.38.230.69
        lbipam.cilium.io/sharing-key: vps-tunnel
        lbipam.cilium.io/sharing-cross-namespace: "*"
      labels:
        expose-public: "true"
      type: LoadBalancer
      ports:
        http:
          port: 5201
