iperf3:
  controllers:
    main:
      containers:
        main:
          image:
            repository: networkstatic/iperf3
            tag: latest@sha256:bc267517f534d9f7cced2669f325799a1fd7fe1d5953c2ca2c6ea1db61affa08
          args: ["-s"]

  service:
    main:
      controller: main
      type: LoadBalancer
      ports:
        http:
          port: 5201
    public:
      controller: main
      annotations:
        lbipam.cilium.io/lb-ipam-ips: 46.38.230.69
        lbipam.cilium.io/sharing-key: vps-tunnel
        lbipam.cilium.io/sharing-cross-namespace: "*"
      labels:
        expose-public: "true"
      type: LoadBalancer
      ports:
        http:
          port: 5201
