- name: Gather instance facts
  ansible.builtin.setup:

- name: Install WireGuard packages
  ansible.builtin.yum:
    name:
      - "wireguard-tools"
    state: present
    update_cache: "true"

- name: Enable WireGuard kernel module
  community.general.modprobe:
    name: wireguard
    state: present
  register: wireguard__register_module_enabled
  until: wireguard__register_module_enabled is succeeded
  retries: 10
  delay: 10
  failed_when: wireguard__register_module_enabled is failure
