- name: Gather instance facts
  ansible.builtin.setup:

- name: Install WireGuard packages
  ansible.builtin.yum:
    name:
      - "wireguard-tools"
    state: present
    update_cache: "true"

- name: Enable WireGuard kernel module
  community.general.modprobe:
    name: wireguard
    state: present
  register: wireguard__register_module_enabled
  until: wireguard__register_module_enabled is succeeded
  retries: 10
  delay: 10
  failed_when: wireguard__register_module_enabled is failure

- name: Register if config/private key already exists on target host
  ansible.builtin.stat:
    path: "/etc/wireguard/wg0.conf"
  register: wireguard__register_config_file

- name: WireGuard private key handling for new keys
  when:
    - not wireguard__register_config_file.stat.exists
    - wireguard_private_key is not defined
  block:
    - name: Generate WireGuard private key
      ansible.builtin.command: "wg genkey"
      register: wireguard__register_private_key

    - name: Set private key fact
      ansible.builtin.set_fact:
        wireguard_private_key: "{{ wireguard__register_private_key.stdout }}"

- name: WireGuard private key handling for existing keys
  when:
    - wireguard__register_config_file.stat.exists
    - wireguard_private_key is not defined
  block:
    - name: Read WireGuard config file
      ansible.builtin.slurp:
        src: "/etc/wireguard/wg0.conf"
      register: wireguard__register_config

    - name: Set private key fact
      ansible.builtin.set_fact:
        wireguard_private_key: "{{ wireguard__register_config['content'] | b64decode | regex_findall('PrivateKey = (.*)') | first }}"

- name: Derive WireGuard public key
  ansible.builtin.command: "wg pubkey"
  args:
    stdin: "{{ wireguard_private_key }}"
  register: wireguard__register_public_key
  changed_when: false
  check_mode: false

- name: Set public key fact
  ansible.builtin.set_fact:
    wireguard__fact_public_key: "{{ wireguard__register_public_key.stdout }}"

- name: Create WireGuard configuration directory
  ansible.builtin.file:
    dest: "/etc/wireguard"
    state: directory
    mode: 0700

- name: Generate WireGuard configuration file
  ansible.builtin.template:
    src: wg.conf.j2
    dest: "/etc/wireguard/wg0.conf"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Load br_netfilter modules
  command: modprobe br_netfilter
  async: 0
  poll: 0
  become: yes

- name: Add 'net.ipv4.ip_forward=1' to /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward=1'

- name: Add 'net.bridge.bridge-nf-call-iptables=1' to /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.bridge.bridge-nf-call-iptables=1'

- name: Reload sysctl settings
  command: sysctl -p

- name: Stop wireguard service
  ansible.builtin.service:
    name: wg-quick@wg0
    state: stopped

- name: Enable wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: true
    state: started
  register: wireguard_service
  until: wireguard_service is succeeded
  retries: 5