versitygw:
  image:
    repository: ghcr.io/versity/versitygw
    tag: v1.3.1@sha256:a86791b684a1dd3c5a255ca755bb51783a72696cf1b5a843f800b08bfd6f921c

  auth:
    existingSecret: versitygw

  gateway:
    virtualDomain: s3.ivanchenko.io

  httpRoute:
    enabled: true
    parentRefs:
      - name: internal-gw
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - s3.ivanchenko.io
      - '*.s3.ivanchenko.io'

  admin:
    enabled: true
    httpRoute:
      enabled: true
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - s3-admin.ivanchenko.io

  webui:
    enabled: true
    apiGateways:
      - https://s3.ivanchenko.io
    adminGateways:
      - https://s3-admin.ivanchenko.io
    httpRoute:
      enabled: true
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - versitygw.ivanchenko.io

helpers:
  infisicalSecrets:
    - name: versitygw
      infisical:
        path: "/versitygw"
  backups:
    - enabled: true
      pvcName: versitygw-data
      resticRepoSuffix: versitygw
