versitygw:
  image:
    repository: ghcr.io/versity/versitygw
    tag: v1.4.0@sha256:6bd4d92bb27ece3097be3c930ea702ebf275288b8711ec91421ccf81d6f36a42

  auth:
    existingSecret: versitygw

  gateway:
    virtualDomain: s3.ivanchenko.io

  httpRoute:
    enabled: true
    parentRefs:
      - name: internal-gw
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - s3.ivanchenko.io
      - '*.s3.ivanchenko.io'

  admin:
    enabled: true
    httpRoute:
      enabled: true
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - s3-admin.ivanchenko.io

  webui:
    enabled: true
    apiGateways:
      - https://s3.ivanchenko.io
    adminGateways:
      - https://s3-admin.ivanchenko.io
    httpRoute:
      enabled: true
      parentRefs:
        - name: internal-gw
          namespace: envoy-gateway
          sectionName: https
      hostnames:
        - versitygw.ivanchenko.io

helpers:
  infisicalSecrets:
    - name: versitygw
      infisical:
        path: "/versitygw"
  backups:
    - enabled: true
      pvcName: versitygw-data
      resticRepoSuffix: versitygw
