apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: actualbudget-secret
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/actualbudget"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: actualbudget-secret
    secretNamespace: actualbudget
