apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: actualbudget-data-restic-config
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/common/restic"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: actualbudget-data-restic-config
    secretNamespace: actualbudget
    template:
      includeAllSecrets: true
      data:
        RESTIC_REPOSITORY: '{{ `{{ .RESTIC_BUCKET.Value }}/actualbudget/data` }}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: actualbudget-data-backup
spec:
  sourcePVC: actualbudget-data
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 14
    repository: actualbudget-data-restic-config
    retain:
      hourly: 12
      daily: 7
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone
    storageClassName: longhorn-ssd-backup
    volumeSnapshotClassName: longhorn-snapshot-vsc
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: actualbudget-bank-sync-restic-config
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/common/restic"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: actualbudget-bank-sync-restic-config
    secretNamespace: actualbudget
    template:
      includeAllSecrets: true
      data:
        RESTIC_REPOSITORY: '{{ `{{ .RESTIC_BUCKET.Value }}/actualbudget/bank-sync` }}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: actualbudget-bank-sync-backup
spec:
  sourcePVC: actualbudget-bank-sync
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 14
    repository: actualbudget-bank-sync-restic-config
    retain:
      hourly: 12
      daily: 7
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone
    storageClassName: longhorn-ssd-backup
    volumeSnapshotClassName: longhorn-snapshot-vsc
