apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: cloudflare-api-token
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: cloudflare-api-token
        property: password
