authentik:
  authentik:
    secret_key: "PleaseGenerateA50CharKey"
    postgresql:
      password: "ThisIsNotASecurePassword"

  envFrom:
    - secretRef:
        name: authentik-secret

  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - host: auth.ivanchenko.io
        paths:
          - path: "/"
            pathType: Prefix

  postgresql:
    enabled: true
    existingSecret: "postgresql-secret"
  redis:
    enabled: true