authentik:
  envFrom:
    - secretRef:
        name: authentik-secret

  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: &host auth.ivanchenko.io
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - secretName: auth-tls
        hosts:
          - *host

  postgresql:
    enabled: true
    existingSecret: "postgresql-secret"

  redis:
    enabled: true
