apiVersion: v2
name: drone
version: 0.0.0
dependencies:
  - name: drone
    repository: https://charts.drone.io
    version: 0.6.5
  - name: drone-runner-docker
    repository: https://charts.drone.io
    version: 0.6.2
