cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

helpers:
  infisicalSecrets:
    - name: cloudflare-api-token
      infisical:
        path: "/cloudflare"
