apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: immich-postgres-user
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/immich/postgres-user"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: immich-postgres-user
    secretNamespace: immich
