# photos backup
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: photo-library-restic-config
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/common/restic"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: photo-library-restic-config
    secretNamespace: immich
    template:
      includeAllSecrets: true
      data:
        RESTIC_REPOSITORY: '{{ `{{ .RESTIC_BUCKET.Value }}/photo-library` }}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: photo-library-backup
spec:
  sourcePVC: photo-library
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: photo-library-restic-config
    retain:
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone
    storageClassName: longhorn-ssd-backup
    volumeSnapshotClassName: longhorn-snapshot-vsc
---
# postgresql backup
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-restic-config
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/common/restic"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: postgres-restic-config
    secretNamespace: immich
    template:
      includeAllSecrets: true
      data:
        RESTIC_REPOSITORY: '{{ `{{ .RESTIC_BUCKET.Value }}/immich/postgres` }}'
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: postgres-backup
spec:
  sourcePVC: immich-postgres-1
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 14
    repository: postgres-restic-config
    retain:
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone
    storageClassName: longhorn-ssd-backup
    volumeSnapshotClassName: longhorn-snapshot-vsc
