enshrouded:
  global:
    nameOverride: enshrouded

  defaultPodOptions:
    automountServiceAccountToken: false

  controllers:
    main:
      pod:
        nodeSelector:
          topology.kubernetes.io/region: game
        tolerations:
          - key: "game"
            operator: "Exists"
            effect: "NoExecute"
        securityContext:
          fsGroup: 4711
          fsGroupChangePolicy: "OnRootMismatch"

      containers:
        main:
          image:
            repository: mornedhels/enshrouded-server
            tag: 0.2.0
          env:
            PUID: 4711
            PGID: 4711
            SERVER_NAME: 88005553535
            SERVER_PASSWORD: secreT
            UPDATE_CRON: "*/30 * * * *"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

  service:
    main:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: game
        metallb.universe.tf/allow-shared-ip: game
      ports:
        http:
          enabled: false
        game:
          enabled: true
          protocol: UDP
          port: 15636
        query:
          enabled: true
          protocol: UDP
          port: 15637

  persistence:
    config:
      enabled: true
      size: 30000Mi
      storageClass: hostpath-ssd-game
      labels:
        recurring-job.longhorn.io/source: enabled
        recurring-job-group.longhorn.io/enshrouded: enabled
      advancedMounts:
        main:
          main:
            - path: /opt/enshrouded
