{{- if $.Values.ghcrSecret.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ $.Values.ghcrSecret.name }}
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ $.Values.global.infisical.projectSlug }}
        envSlug: {{ $.Values.global.infisical.envSlug }}
        secretsPath: {{ $.Values.ghcrSecret.infisicalPath | quote }}
      credentialsRef:
        secretName: {{ $.Values.global.infisical.credentialsRef.secretName }}
        secretNamespace: {{ $.Values.global.infisical.credentialsRef.secretNamespace }}
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: {{ $.Values.ghcrSecret.name }}
    secretNamespace: {{ $.Release.Namespace }}
    secretType: kubernetes.io/dockerconfigjson
    template:
      includeAllSecrets: true
{{- end }}
