ingress-nginx-home:
  controller:
    allowSnippetAnnotations: true

    nodeSelector:
      topology.kubernetes.io/region: home

    tolerations:
      - key: "media"
        operator: "Exists"
        effect: "NoExecute"

    ingressClassResource:
      name: nginx-home
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-home"

    ingressClass: nginx-home

    service:
      annotations:
        metallb.universe.tf/address-pool: home
        metallb.universe.tf/allow-shared-ip: home

    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true