ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

ingress-nginx-home:
  controller:
    ingressClass: nginx-home
    electionID: ingress-controller-leader-home

    service:
      annotations:
        metallb.universe.tf/address-pool: home

    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true