apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: victoria-logs
spec:
  retentionPeriod: "30d"
  extraArgs:
    syslog.listenAddr.udp: ":5514"
  storage:
    resources:
      requests:
        storage: 50Gi
  useDefaultResources: false
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      memory: 1Gi
