apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: alerting-routing
  namespace: telemetry
spec:
  route:
    receiver: telegram
    group_by: [alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: healthchecks
        matchers:
          - alertname="Watchdog"
        group_wait: 0s
        group_interval: 1m
        repeat_interval: 5m
  receivers:
    - name: telegram
      telegram_configs:
        - bot_token:
            name: alertmanager-secrets
            key: TELEGRAM_BOTTOKEN
          chat_id: 236266523
          parse_mode: HTML
          send_resolved: true
    - name: healthchecks
      webhook_configs:
        - url_secret:
            name: alertmanager-secrets
            key: HEALTHCHECKS_URL
          send_resolved: false
