apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kube-job-failed-once
  namespace: telemetry
spec:
  groups:
    - name: kube-job-failed-once
      rules:
        - alert: KubeJobFailed
          expr: |
            kube_job_failed{job="kube-state-metrics", job_name!="cilium-install", condition="true"} > 0
            and ignoring(__name__)
            changes(kube_job_failed{job="kube-state-metrics", job_name!="cilium-install", condition="true"}[6h]) > 0
          labels:
            severity: warning
          annotations:
            summary: {{ `'Job {{ $labels.namespace }}/{{ $labels.job_name }} failed'` }}
            description: 'A Job failed within the last 6h. After investigating, delete the Job object to clear this alert and stop it accumulating in etcd.'
